# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-patrol" do
  name "git-patrol"
  desc "Automated git repository synchronization — periodic sync, conflict resolution, hooks, and parallel execution"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/git-patrol"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-patrol"

  on_macos do
    url "https://github.com/codefuturist/monorepository/releases/download/git-patrol%2Fv#{version}/git-patrol_#{version}_Darwin_all.tar.gz"
    sha256 "53b2fea9ae18eae9ae52ccec25e616d112648e3c3c267261ad4bdd2ed1afaff1"
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-patrol"]
  end

  # No zap stanza required
end
