# This file was generated by GoReleaser. DO NOT EDIT.
cask "porter" do
  require "download_strategy"

  class GitHubPrivateReleaseStrategy < CurlDownloadStrategy
    require "utils/github"

    def initialize(url, name, version, **meta)
      super
      @pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid GitHub release URL: #{@url}" unless @url =~ @pattern
      _, @owner, @repo, @tag, @filename = *@url.match(@pattern)
      @token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required to install porter (private release)." unless @token
    end

    def _fetch(url:, resolved_url:, timeout:)
      meta = GitHub::API.open_rest("https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}")
      asset = meta["assets"].find { |a| a["name"] == @filename }
      raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}." unless asset
      curl_download "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset["id"]}",
                    "--header", "Accept: application/octet-stream",
                    "--header", "Authorization: Bearer #{@token}",
                    to: temporary_path
    end
  end

  version "0.1.1"

  on_macos do
    app "Porter.app"
  end

  on_macos do
    on_arm do
      sha256 "f507e775bb9fc4d9bf3d2c7d9df7575192a87259383768bfb3658a71e3cedcaf"
      url "https://github.com/codefuturist/porter/releases/download/v#{version}/Porter_#{version}.dmg",
        using: GitHubPrivateReleaseStrategy
    end
  end

  name "porter"
  desc "One place for every package manager on your Mac"
  homepage "https://github.com/codefuturist/porter"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Porter.app"]
  end

  # No zap stanza required

  caveats <<~EOS
    Porter is signed ad-hoc, not notarized. If macOS still blocks the first
    launch, right-click Porter in Applications and choose Open once.
  EOS
end
