# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Bwtid < Formula
  desc "Touch ID for your Bitwarden master password (rbw / bw CLI / MCP, with a password fallback)"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/bwtid"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/codefuturist/monorepository/releases/download/bwtid%2Fv0.2.0/bwtid_0.2.0_darwin_universal.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "207516a9708379010b63741eea6bf728b21d9692ee9cf16bb3d9ed1e05c8f1d8"

    define_method(:install) do
      bin.install "bwtid"
      # Busybox-style symlinks: one binary dispatches on argv[0].
      %w[bw-unlock bw-lock bw-login bw-touchid-enroll bw-touchid-gate pinentry-touchid].each do |n|
        bin.install_symlink "bwtid" => n
      end
      generate_completions_from_executable(bin/"bwtid", "--generate-completion-script", shells: [:bash, :zsh, :fish])
    end
  end

  def caveats
    <<~EOS
      Enroll once:   bw-touchid-enroll
      Point rbw:     rbw config set pinentry "$(command -v pinentry-touchid)"
      Diagnose:      bwtid doctor
      Touch ID here is app-enforced (not a Secure-Enclave ACL); see the README's
      security model. The binary is ad-hoc signed — if macOS quarantines it:
        xattr -dr com.apple.quarantine "$(command -v bwtid)"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bwtid --version")
  end
end
