# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Bwtid < Formula
  desc "Touch ID for your Bitwarden master password (rbw / bw CLI / MCP, with a password fallback)"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/bwtid"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/codefuturist/monorepository/releases/download/bwtid%2Fv0.1.0/bwtid_0.1.0_darwin_universal.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fdae8b4e0f6c60195c44aa375ee062cfb67cc1d88d444e8fad8df18246705e17"

    define_method(:install) do
      bin.install "bwtid"
      # Busybox-style symlinks: one binary dispatches on argv[0].
      %w[bw-unlock bw-lock bw-touchid-enroll bw-touchid-gate pinentry-touchid].each do |n|
        bin.install_symlink "bwtid" => n
      end
    end
  end

  def caveats
    <<~EOS
      Enroll once:   bw-touchid-enroll
      Point rbw:     rbw config set pinentry "$(command -v pinentry-touchid)"
      Diagnose:      bwtid doctor
      Touch ID here is app-enforced (not a Secure-Enclave ACL); see the README's
      security model. The binary is ad-hoc signed — if macOS quarantines it:
        xattr -dr com.apple.quarantine "$(command -v bwtid)"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bwtid --version")
  end
end
