# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Encore < Formula
  desc "Record and replay macOS keyboard and mouse events"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/Encore"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/codefuturist/monorepository/releases/download/encore%2Fv1.1.0/encore_1.1.0_darwin_universal.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "bf907afbb2572ab98d85d2cd614b1759fdb42d630e931ab5bece5920c5b0a69b"

    define_method(:install) do
      bin.install "encore"
      bin.install "encore-mcp"
    end
  end

  def caveats
    <<~EOS
      Encore drives macOS input and reads the screen, so grant your terminal:
        • Accessibility — all input and element commands
        • Screen Recording — find text/image, screenshot, visual workflows
      in System Settings → Privacy & Security, then fully restart the
      terminal (a new Screen Recording grant needs a restart to apply).

      encore-mcp (the Model Context Protocol server) is installed alongside;
      point your MCP client at: #{opt_bin}/encore-mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/encore --version")
  end
end
