# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class GitPatrol < Formula
  desc "Automated git repository synchronization — periodic sync, conflict resolution, hooks, and parallel execution"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/git-patrol"
  version "0.2.1"
  license "MIT"

  on_macos do
    url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "69154d97929b68e042e6ca8569400537aced9b6bf94de83fdc950b14b3f6cf3c"

    define_method(:install) do
      bin.install "git-patrol"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b2cdb4db265854a2553847cbc92b498648fc97d3fce9eedbd7477896a4d264cd"
      define_method(:install) do
        bin.install "git-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Linux_aarch64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fbe5f33a1570d4d1bd8a129add24cb2c9fa4c168560abf9499031158b976266e"
      define_method(:install) do
        bin.install "git-patrol"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-patrol --version")
  end
end
