# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"

class GitPatrol < Formula
  desc "Automated git repository synchronization — periodic sync, conflict resolution, hooks, and parallel execution"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/git-patrol"
  version "0.2.0"
  license "MIT"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    url "https://github.com/codefuturist/monorepository/releases/download/git-patrol%2Fv0.2.0/git-patrol_0.2.0_Darwin_all.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "53b2fea9ae18eae9ae52ccec25e616d112648e3c3c267261ad4bdd2ed1afaff1"
  end

  def install
    bin.install "git-patrol"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-patrol --version")
  end
end
