# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class GitPatrol < Formula
  desc "Automated git repository synchronization — periodic sync, conflict resolution, hooks, and parallel execution"
  homepage "https://github.com/codefuturist/monorepository/tree/main/apps/cli/git-patrol"
  version "0.2.1"
  license "MIT"

  on_macos do
    url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "02379ed0e1a17c08b67d2746d0ac344558c4dc36298724504e1b69479e22f954"

    define_method(:install) do
      bin.install "git-patrol"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f50c4b5fef461e2506c9fcb904479efcfad495703dea299b6f3766076a35481"
      define_method(:install) do
        bin.install "git-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codefuturist/monorepository/releases/download/v0.2.1/git-patrol_0.2.1_Linux_aarch64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6f34a31b425d5db5da81ce180c9571e5813dfb0e9295e40fd3ba06d1fea6501e"
      define_method(:install) do
        bin.install "git-patrol"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-patrol --version")
  end
end
