name: Update Homebrew Formula

on:
  repository_dispatch:
    types: [formula-update]
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula name to update'
        required: true
        default: 'packr'
      version:
        description: 'Version to update to'
        required: true
      url:
        description: 'Download URL'
        required: true
      sha256:
        description: 'SHA256 checksum'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Update formula
        run: |
          FORMULA="${{ github.event.inputs.formula || github.event.client_payload.formula }}"
          VERSION="${{ github.event.inputs.version || github.event.client_payload.version }}"
          URL="${{ github.event.inputs.url || github.event.client_payload.url }}"
          SHA256="${{ github.event.inputs.sha256 || github.event.client_payload.sha256 }}"
          
          # Update the formula file
          FORMULA_FILE="Formula/${FORMULA}.rb"
          
          if [ ! -f "$FORMULA_FILE" ]; then
            echo "Formula file not found: $FORMULA_FILE"
            exit 1
          fi
          
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION}\"/" "$FORMULA_FILE"
          
          # Update URL
          sed -i "s|url \"https://github.com/.*/releases/download/.*\"|url \"${URL}\"|" "$FORMULA_FILE"
          
          # Update SHA256
          sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" "$FORMULA_FILE"
          
          echo "Updated ${FORMULA} to version ${VERSION}"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          FORMULA="${{ github.event.inputs.formula || github.event.client_payload.formula }}"
          VERSION="${{ github.event.inputs.version || github.event.client_payload.version }}"
          
          git add Formula/*.rb
          git commit -m "Update ${FORMULA} to ${VERSION}" || echo "No changes to commit"
          git push
